In [1]:
import pandas as pd

## DATAFRAME

In [4]:
diretorio_apple = "../data/apple_products_pricing_2020_2026.csv"
diretorio_student = "../data/student_burnout_dropout_dataset_2.csv"

df_apple = pd.read_csv(diretorio_apple)
df_apple

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [5]:
df_studante = pd.read_csv(diretorio_student)
df_studante

,Student_ID,Age,Gender,Year_of_Study,Department,Residence_Type,Attendance_Percent,Study_Hours_Per_Day,Previous_GPA,Backlogs,...,Family_Income_Bracket,Financial_Stress_Score,Family_Support_Score,Stress_Level,Anxiety_Score,Motivation_Score,Peer_Pressure_Score,Counseling_Access,Burnout_Level,Dropout_Risk
0,STU00001,23,Female,2,Science,Hostel,93.0,4.1,7.13,2.0,...,Upper-Middle,5.5,10.0,4.0,NaN,7.0,NaN,No,Low,No
1,STU00002,20,Female,4,Engineering,Day Scholar,94.3,0.0,10.00,0.0,...,Low,3.7,4.0,5.5,5.1,9.3,2.8,Yes,Medium,Yes
2,STU00003,24,Male,2,Business,PG/Rented,61.2,2.6,8.02,0.0,...,Middle,4.8,8.1,9.0,5.2,5.7,5.4,No,High,Yes
3,STU00004,21,Female,4,Medicine,Hostel,66.9,3.1,5.34,1.0,...,Lower-Middle,7.0,6.6,2.8,4.2,5.1,3.9,No,High,Yes
4,STU00005,23,Female,1,Engineering,NaN,84.8,2.9,4.45,1.0,...,Lower-Middle,1.3,7.3,0.9,6.4,8.1,5.1,No,Low,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,STU00796,21,Male,4,Law,PG/Rented,68.1,0.8,5.84,0.0,...,Middle,3.3,NaN,6.6,4.8,10.0,4.9,Yes,Low,No
796,STU00797,25,Male,2,Engineering,Hostel,91.0,0.0,7.04,1.0,...,Middle,4.3,NaN,6.7,NaN,3.3,4.6,Yes,High,Yes
797,STU00798,17,Female,4,Arts,PG/Rented,NaN,4.9,3.51,1.0,...,Low,7.6,7.4,6.0,7.3,4.2,4.5,No,High,Yes
798,STU00799,25,Female,3,Science,Day Scholar,84.9,NaN,9.24,1.0,...,Middle,6.3,7.4,6.8,4.7,6.9,NaN,No,Low,No
799,STU00800,24,Female,1,Science,PG/Rented,NaN,3.1,5.80,1.0,...,Lower-Middle,6.1,10.0,4.9,4.2,6.8,5.1,No,Medium,No

## SERIES

In [6]:
df_apple["Platform"]

0        Flipkart
1        Flipkart
2          Amazon
3          Amazon
4          Amazon
           ...
79995    Flipkart
79996    Flipkart
79997      Amazon
79998    Flipkart
79999    Flipkart
Name: Platform, Length: 80000, dtype: str

## APRENDENDO A PERGUNTAR

In [7]:
df_apple.head(10)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
5,2020-09-26,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.29,43149.46,-1.7,NaN,In Stock,4.7,45
6,2020-09-27,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.06,42587.59,-0.9,NaN,In Stock,4.8,60
7,2020-09-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,312.11,26276.64,27.2,NaN,In Stock,4.4,146
8,2020-10-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,323.84,31855.01,24.5,Big Billion Days,In Stock,4.7,95
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133

In [8]:
df_apple["Product_Category"].value_counts()

Product_Category
iPhone    28589
Mac       18020
Watch     17865
iPad      15526
Name: count, dtype: int64

In [10]:
df_apple.nunique()

Date                  2130
Platform                 2
Product_Category         4
Model_Name              31
Condition                2
Launch_Price_USD         9
Launch_Price_INR         9
Current_Price_USD    49611
Current_Price_INR    79626
Discount_Pct           695
Sale_Event               4
Stock_Status             3
Rating                  12
Reviews_Count         8698
dtype: int64

In [11]:
df_apple.memory_usage()

Index                   132
Date                 640000
Platform             640000
Product_Category     640000
Model_Name           640000
Condition            640000
Launch_Price_USD     640000
Launch_Price_INR     640000
Current_Price_USD    640000
Current_Price_INR    640000
Discount_Pct         640000
Sale_Event           640000
Stock_Status         640000
Rating               640000
Reviews_Count        640000
dtype: int64

In [13]:
pergunta = df_apple["Rating"] > 4.8
df_apple[pergunta]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133
13,2020-10-03,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,324.80,32134.64,24.3,Big Billion Days,In Stock,4.9,62
46,2020-10-25,Flipkart,iPhone,iPhone 12 64GB,New,799,78302,806.28,77725.70,-0.9,NaN,In Stock,4.9,31
48,2020-10-26,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.26,41708.05,-1.0,NaN,In Stock,4.9,181
50,2020-10-26,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,595.03,59012.48,0.7,NaN,In Stock,4.9,101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79919,2026-07-30,Flipkart,iPhone,iPhone 16 Pro 256GB,New,1099,107702,997.19,97000.04,9.3,NaN,In Stock,4.9,2538
79939,2026-07-31,Flipkart,Watch,Apple Watch Ultra,New,799,78302,500.02,48863.90,37.4,NaN,In Stock,4.9,3565
79943,2026-07-31,Amazon,Watch,Apple Watch Ultra 2,New,799,78302,601.12,58320.38,24.8,NaN,In Stock,4.9,4359
79965,2026-07-31,Flipkart,iPad,iPad Pro 11-inch (M4) 256GB,New,999,97902,787.20,76806.12,21.2,NaN,In Stock,4.9,2828
79971,2026-07-31,Amazon,iPhone,iPhone 12 Pro 128GB,New,999,97902,593.44,59085.11,40.6,NaN,Low Stock,4.9,7248

In [14]:
filtro_amazon = df_apple["Platform"] == "Amazon"
df_apple[filtro_amazon]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133
10,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,385.37,37753.37,10.2,Great Indian Festival,In Stock,4.5,57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79990,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,844.47,84171.70,0.5,NaN,In Stock,4.7,893
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79994,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,837.57,82448.67,1.3,NaN,In Stock,4.3,1407
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020

In [15]:
filtro_maior_mil_usd = df_apple["Current_Price_USD"] > 1000
df_apple[filtro_maior_mil_usd]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
41,2020-10-24,Amazon,iPhone,iPhone 12 Pro 128GB,New,999,97902,1002.99,98268.29,-0.4,NaN,In Stock,4.3,27
42,2020-10-24,Amazon,iPhone,iPhone 12 Pro 128GB,New,999,97902,1018.59,101731.95,-2.0,NaN,In Stock,4.7,69
43,2020-10-24,Flipkart,iPhone,iPhone 12 Pro 128GB,New,999,97902,1008.45,97646.38,-0.9,NaN,Out of Stock,4.8,91
54,2020-10-27,Amazon,iPhone,iPhone 12 Pro 128GB,New,999,97902,1010.02,97930.53,-1.1,NaN,In Stock,4.5,98
60,2020-10-28,Flipkart,iPhone,iPhone 12 Pro 128GB,New,999,97902,1009.63,97164.80,-1.1,NaN,In Stock,4.4,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79952,2026-07-31,Flipkart,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,1913.92,190679.41,4.3,NaN,In Stock,4.5,3166
79953,2026-07-31,Flipkart,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,1870.03,184162.22,6.5,NaN,In Stock,4.7,2349
79954,2026-07-31,Amazon,Mac,MacBook Pro 14-inch M4 Pro 512GB,Renewed/Refurbished,1999,195902,1640.94,136734.61,17.9,NaN,In Stock,4.3,1035
79955,2026-07-31,Amazon,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,1913.47,187111.67,4.3,NaN,Low Stock,4.3,2214
79984,2026-07-31,Flipkart,iPhone,iPhone 15 Pro Max 256GB,New,1199,117502,1018.87,100946.12,15.0,NaN,Low Stock,4.5,4403

In [16]:
df_apple[df_apple["Current_Price_USD"] < 500]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79970,2026-07-31,Flipkart,iPhone,iPhone 12 64GB,Renewed/Refurbished,799,78302,394.54,33400.54,50.6,NaN,Low Stock,4.5,4714
79974,2026-07-31,Amazon,iPhone,iPhone 13 128GB,New,799,78302,486.99,48312.89,39.1,NaN,In Stock,4.8,4381
79975,2026-07-31,Amazon,iPhone,iPhone 13 128GB,New,799,78302,479.01,46060.59,40.0,NaN,Out of Stock,4.8,6118
79981,2026-07-31,Flipkart,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,451.76,39016.28,43.5,NaN,In Stock,4.5,3803
79983,2026-07-31,Amazon,iPhone,iPhone 15 128GB,Renewed/Refurbished,799,78302,449.58,38863.40,43.7,NaN,In Stock,4.2,4641

In [17]:
df_apple[df_apple["Stock_Status"] != "In Stock"]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
14,2020-10-04,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,265.10,22614.35,38.2,Great Indian Festival,Low Stock,4.4,112
15,2020-10-06,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,348.69,33665.07,18.7,Great Indian Festival,Out of Stock,4.4,127
19,2020-10-07,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,308.34,25820.76,28.1,Big Billion Days,Out of Stock,4.0,157
20,2020-10-08,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,351.25,34046.78,18.1,Big Billion Days,Out of Stock,4.2,163
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79986,2026-07-31,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,693.49,69317.61,13.2,NaN,Low Stock,4.5,1162
79988,2026-07-31,Amazon,iPhone,iPhone 16 128GB,Renewed/Refurbished,799,78302,525.79,44818.21,34.2,NaN,Low Stock,3.9,2016
79989,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,843.77,83516.88,0.6,NaN,Out of Stock,4.7,1060
79993,2026-07-31,Amazon,iPhone,iPhone 17 128GB,New,849,83202,853.13,82031.15,-0.5,NaN,Low Stock,4.7,1428
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [23]:
f1 = df_apple["Platform"] == "Amazon"
f2 = df_apple["Rating"] > 4.8

f3 = (f1 & f2)
# df_apple[f3]
df_apple[(df_apple["Platform"] == "Amazon") & (df_apple["Rating"] > 4.8)]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133
48,2020-10-26,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.26,41708.05,-1.0,NaN,In Stock,4.9,181
50,2020-10-26,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,595.03,59012.48,0.7,NaN,In Stock,4.9,101
57,2020-10-28,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,587.31,57601.81,2.0,NaN,In Stock,4.9,109
201,2020-11-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,380.69,37375.09,11.3,Black Friday,In Stock,4.9,308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79898,2026-07-30,Amazon,iPhone,iPhone 13 128GB,New,799,78302,486.80,47195.71,39.1,NaN,Low Stock,4.9,5460
79902,2026-07-30,Amazon,iPhone,iPhone 14 128GB,New,799,78302,498.93,48521.42,37.6,NaN,Low Stock,4.9,6834
79917,2026-07-30,Amazon,iPhone,iPhone 16 128GB,New,799,78302,692.42,66677.66,13.3,NaN,In Stock,4.9,1174
79943,2026-07-31,Amazon,Watch,Apple Watch Ultra 2,New,799,78302,601.12,58320.38,24.8,NaN,In Stock,4.9,4359
79971,2026-07-31,Amazon,iPhone,iPhone 12 Pro 128GB,New,999,97902,593.44,59085.11,40.6,NaN,Low Stock,4.9,7248

In [ ]:
df_apple[(df_apple["Product_Category"] == "Iphone") | 
         (df_apple["Product_Category"] == "iPad") |
         (df_apple["Product_Category"] == "Mac")
         ]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
34,2020-10-23,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,599.55,58434.06,-0.1,NaN,Out of Stock,4.6,83
40,2020-10-24,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,591.99,57562.43,1.2,NaN,Out of Stock,4.4,95
49,2020-10-26,Flipkart,iPad,iPad Air (4th Gen) 64GB,Renewed/Refurbished,599,58702,506.91,42461.72,15.4,NaN,In Stock,4.0,26
50,2020-10-26,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,595.03,59012.48,0.7,NaN,In Stock,4.9,101
52,2020-10-27,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,605.15,59466.82,-1.0,NaN,In Stock,4.5,109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79965,2026-07-31,Flipkart,iPad,iPad Pro 11-inch (M4) 256GB,New,999,97902,787.20,76806.12,21.2,NaN,In Stock,4.9,2828
79966,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,882.16,85191.56,26.4,NaN,In Stock,4.5,6421
79967,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,916.50,90829.31,23.6,NaN,In Stock,4.3,6633
79968,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,Renewed/Refurbished,1199,117502,741.15,62937.68,38.2,NaN,Low Stock,4.2,5049
79969,2026-07-31,Amazon,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,897.55,88142.32,25.1,NaN,Low Stock,4.6,4054

In [30]:
df_apple[df_apple["Product_Category"].isin([
    "Iphone",
    "iPad",
    "Mac"
])
]

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
34,2020-10-23,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,599.55,58434.06,-0.1,NaN,Out of Stock,4.6,83
40,2020-10-24,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,591.99,57562.43,1.2,NaN,Out of Stock,4.4,95
49,2020-10-26,Flipkart,iPad,iPad Air (4th Gen) 64GB,Renewed/Refurbished,599,58702,506.91,42461.72,15.4,NaN,In Stock,4.0,26
50,2020-10-26,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,595.03,59012.48,0.7,NaN,In Stock,4.9,101
52,2020-10-27,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,605.15,59466.82,-1.0,NaN,In Stock,4.5,109
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79965,2026-07-31,Flipkart,iPad,iPad Pro 11-inch (M4) 256GB,New,999,97902,787.20,76806.12,21.2,NaN,In Stock,4.9,2828
79966,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,882.16,85191.56,26.4,NaN,In Stock,4.5,6421
79967,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,916.50,90829.31,23.6,NaN,In Stock,4.3,6633
79968,2026-07-31,Flipkart,iPad,iPad Pro 12.9-inch (M2) 256GB,Renewed/Refurbished,1199,117502,741.15,62937.68,38.2,NaN,Low Stock,4.2,5049
79969,2026-07-31,Amazon,iPad,iPad Pro 12.9-inch (M2) 256GB,New,1199,117502,897.55,88142.32,25.1,NaN,Low Stock,4.6,4054

In [ ]:
df_apple["Discount_USD"] = (
    df_apple["Launch_Price_USD"] - df_apple["Current_Price_USD"]
)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count,Discount_USD
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40,-6.81
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84,-7.49
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110,6.27
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111,4.00
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35,-7.22
5,2020-09-26,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.29,43149.46,-1.7,NaN,In Stock,4.7,45,-7.29
6,2020-09-27,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.06,42587.59,-0.9,NaN,In Stock,4.8,60,-4.06
7,2020-09-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,312.11,26276.64,27.2,NaN,In Stock,4.4,146,116.89
8,2020-10-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,323.84,31855.01,24.5,Big Billion Days,In Stock,4.7,95,105.16
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133,38.49

In [33]:
df_apple["price_with_shipping"] = (df_apple["Current_Price_USD"] + 30)
df_apple

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count,Discount_USD,price_with_shipping
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40,-6.81,465.81
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84,-7.49,466.49
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110,6.27,452.73
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111,4.00,455.00
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35,-7.22,466.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346,-12.39,891.39
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802,16.50,862.50
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020,191.70,687.30
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710,139.51,739.49
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022,14.05,864.95

In [34]:
df_apple = df_apple.rename(
    columns={
        "Date": "data",
        "Platform": "plataforma",
        "Product_Category": "categoria",
        "Model_Name": "modelo",
        "Condition": "condicao",
        "Launch_Price_USD": "preco_lancamento_usd",
        "Launch_Price_INR": "preco_lancamento_inr",
        "Current_Price_USD": "preco_atual_usd",
        "Current_Price_INR": "preco_atual_inr",
        "Discount_Pct": "percentual_desconto",
        "Sale_Event": "evento_promocional",
        "Stock_Status": "status_estoque",
        "Rating": "avaliacao",
        "Reviews_Count": "quantidade_avaliacoes",
    }
)
df_apple = df_apple.rename(columns={"Discount_USD": "desconto_dolar",
                                    "price_with_shipping": "preco_com_taxa_frete"})

df_apple.columns

Index(['data', 'plataforma', 'categoria', 'modelo', 'condicao',
       'preco_lancamento_usd', 'preco_lancamento_inr', 'preco_atual_usd',
       'preco_atual_inr', 'percentual_desconto', 'evento_promocional',
       'status_estoque', 'avaliacao', 'quantidade_avaliacoes',
       'desconto_dolar', 'preco_com_taxa_frete'],
      dtype='str')

In [37]:
df_apple.sort_values(
    "preco_atual_usd",
    ascending=False
)

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete
21797,2023-12-17,Amazon,Mac,MacBook Pro 14-inch M3 Pro 512GB,New,1999,195902,2038.97,201118.32,-2.0,NaN,In Stock,4.4,170,-39.97,2068.97
21296,2023-12-05,Amazon,Mac,MacBook Pro 14-inch M3 Pro 512GB,New,1999,195902,2038.97,202775.10,-2.0,NaN,In Stock,4.4,169,-39.97,2068.97
55303,2025-08-19,Flipkart,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,2038.90,202155.09,-2.0,NaN,Low Stock,4.3,1322,-39.90,2068.90
54844,2025-08-12,Amazon,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,2038.90,195894.74,-2.0,NaN,In Stock,4.6,631,-39.90,2068.90
26040,2024-03-27,Amazon,Mac,MacBook Pro 14-inch M3 Pro 512GB,New,1999,195902,2038.83,199632.47,-2.0,NaN,In Stock,4.9,634,-39.83,2068.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35140,2024-10-03,Flipkart,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,118.03,10058.69,64.1,Big Billion Days,Low Stock,3.9,3511,210.97,148.03
61862,2025-11-22,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,117.65,10040.71,64.2,Black Friday,Out of Stock,4.2,4317,211.35,147.65
58657,2025-10-08,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,113.07,9444.39,65.6,Great Indian Festival,Low Stock,3.9,6131,215.93,143.07
59102,2025-10-14,Flipkart,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,111.14,9409.24,66.2,Big Billion Days,Low Stock,4.5,4381,217.86,141.14
31229,2024-07-17,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,109.93,9157.68,66.6,Prime Day,Out of Stock,4.4,2293,219.07,139.93

In [39]:
df_apple["preco_atual_usd"].max()

np.float64(2038.97)

In [43]:
df_apple.sort_values(
    by= "avaliacao",
    ascending=False
).head(10)

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete
79919,2026-07-30,Flipkart,iPhone,iPhone 16 Pro 256GB,New,1099,107702,997.19,97000.04,9.3,NaN,In Stock,4.9,2538,101.81,1027.19
79917,2026-07-30,Amazon,iPhone,iPhone 16 128GB,New,799,78302,692.42,66677.66,13.3,NaN,In Stock,4.9,1174,106.58,722.42
79939,2026-07-31,Flipkart,Watch,Apple Watch Ultra,New,799,78302,500.02,48863.90,37.4,NaN,In Stock,4.9,3565,298.98,530.02
46,2020-10-25,Flipkart,iPhone,iPhone 12 64GB,New,799,78302,806.28,77725.70,-0.9,NaN,In Stock,4.9,31,-7.28,836.28
13,2020-10-03,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,324.80,32134.64,24.3,Big Billion Days,In Stock,4.9,62,104.20,354.80
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133,38.49,420.51
44916,2025-03-08,Flipkart,iPhone,iPhone 16 128GB,New,799,78302,792.70,76996.47,0.8,NaN,In Stock,4.9,966,6.30,822.70
57,2020-10-28,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,587.31,57601.81,2.0,NaN,In Stock,4.9,109,11.69,617.31
50,2020-10-26,Amazon,iPad,iPad Air (4th Gen) 64GB,New,599,58702,595.03,59012.48,0.7,NaN,In Stock,4.9,101,3.97,625.03
48,2020-10-26,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.26,41708.05,-1.0,NaN,In Stock,4.9,181,-4.26,463.26

In [44]:
df_apple.sort_values(
    by=["plataforma", "preco_atual_usd"],
    ascending=False
)

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete
55303,2025-08-19,Flipkart,Mac,MacBook Pro 14-inch M4 Pro 512GB,New,1999,195902,2038.90,202155.09,-2.0,NaN,Low Stock,4.3,1322,-39.90,2068.90
30877,2024-07-10,Flipkart,Mac,MacBook Pro 14-inch M3 Pro 512GB,New,1999,195902,2038.82,198186.40,-2.0,NaN,In Stock,4.8,605,-39.82,2068.82
4533,2022-02-23,Flipkart,Mac,MacBook Pro 14-inch M1 Pro 512GB,New,1999,195902,2038.75,201458.46,-2.0,NaN,In Stock,4.8,598,-39.75,2068.75
21391,2023-12-07,Flipkart,Mac,MacBook Pro 14-inch M2 Pro 512GB,New,1999,195902,2038.74,197910.43,-2.0,NaN,In Stock,4.6,1616,-39.74,2068.74
26658,2024-04-10,Flipkart,Mac,MacBook Pro 14-inch M3 Pro 512GB,New,1999,195902,2038.69,200750.57,-2.0,NaN,In Stock,4.9,510,-39.69,2068.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58307,2025-10-03,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,121.94,10169.08,62.9,Great Indian Festival,In Stock,4.2,6366,207.06,151.94
31290,2024-07-18,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,120.24,10368.62,63.5,Prime Day,Out of Stock,3.9,3126,208.76,150.24
61862,2025-11-22,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,117.65,10040.71,64.2,Black Friday,Out of Stock,4.2,4317,211.35,147.65
58657,2025-10-08,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,113.07,9444.39,65.6,Great Indian Festival,Low Stock,3.9,6131,215.93,143.07
31229,2024-07-17,Amazon,iPad,iPad (9th Gen) 64GB,Renewed/Refurbished,329,32242,109.93,9157.68,66.6,Prime Day,Out of Stock,4.4,2293,219.07,139.93

In [45]:
df_apple_tratado = df_apple.drop(columns = ["preco_lancamento_inr", "preco_atual_inr"])
df_apple_tratado.head()

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_atual_usd,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,435.81,-1.6,NaN,In Stock,4.7,40,-6.81,465.81
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,436.49,-1.7,NaN,Out of Stock,4.6,84,-7.49,466.49
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,422.73,1.5,NaN,In Stock,4.4,110,6.27,452.73
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,425.00,0.9,NaN,In Stock,4.8,111,4.00,455.00
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,436.22,-1.7,NaN,In Stock,4.7,35,-7.22,466.22

In [47]:
df_apple["evento_promocional"] = df_apple["evento_promocional"].fillna("sem promoção")
df_apple

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,sem promoção,In Stock,4.7,40,-6.81,465.81
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,sem promoção,Out of Stock,4.6,84,-7.49,466.49
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,sem promoção,In Stock,4.4,110,6.27,452.73
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,sem promoção,In Stock,4.8,111,4.00,455.00
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,sem promoção,In Stock,4.7,35,-7.22,466.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,sem promoção,In Stock,4.7,1346,-12.39,891.39
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,sem promoção,In Stock,4.7,802,16.50,862.50
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,sem promoção,In Stock,4.2,1020,191.70,687.30
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,sem promoção,In Stock,3.9,710,139.51,739.49
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,sem promoção,Low Stock,4.8,1022,14.05,864.95

In [48]:
df_apple.dtypes

data                         str
plataforma                   str
categoria                    str
modelo                       str
condicao                     str
preco_lancamento_usd       int64
preco_lancamento_inr       int64
preco_atual_usd          float64
preco_atual_inr          float64
percentual_desconto      float64
evento_promocional           str
status_estoque               str
avaliacao                float64
quantidade_avaliacoes      int64
desconto_dolar           float64
preco_com_taxa_frete     float64
dtype: object

In [55]:
df_apple["data"] = pd.to_datetime(df_apple["data"],
                                  format="%Y-%m-%d",
                                  errors="coerce")

In [51]:
datas = pd.Series([
    "25/07/2026",
    "2026-08-10",
    "15-09-2026",
    "05/07/2026",
    "data desconhecida"
])
datas_convertidas = pd.to_datetime(datas,
                                format="mixed",
                                dayfirst=True,
                                errors="coerce"
                                )
comparacoes = pd.DataFrame({
    "data_original": datas,
    "data_convertida": datas_convertidas
})

comparacoes

       data_original data_convertida
0         25/07/2026      2026-07-25
1         2026-08-10      2026-10-08
2         15-09-2026      2026-09-15
3         05/07/2026      2026-07-05
4  data desconhecida             NaT

In [56]:
df_apple["ano"] = df_apple["data"].dt.year
df_apple.head()

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete,ano
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,sem promoção,In Stock,4.7,40,-6.81,465.81,2020
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,sem promoção,Out of Stock,4.6,84,-7.49,466.49,2020
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,sem promoção,In Stock,4.4,110,6.27,452.73,2020
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,sem promoção,In Stock,4.8,111,4.00,455.00,2020
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,sem promoção,In Stock,4.7,35,-7.22,466.22,2020

In [64]:
df_apple["preco_atual_usd"] = (df_apple["preco_atual_usd"].astype("object"))
df_apple.loc[0, "preco_atual_usd"] = "Mudei o dado"
df_apple.head(1)
# 	data	plataforma	categoria	modelo	condicao	preco_lancamento_usd	preco_lancamento_inr	preco_atual_usd	preco_atual_inr	percentual_desconto	evento_promocional	status_estoque	avaliacao	quantidade_avaliacoes	desconto_dolar	preco_com_taxa_frete	ano
# 0	2020-09-19	Flipkart	Watch	Apple Watch Series 6 (44mm)	New	429	42042	Mudei o dado	43322.41	-1.6	sem promoção	In Stock	4.7	40	-6.81	465.81	2020

# df_apple["preco_atual_usd"] = (df_apple["preco_atual_usd"].astype("float"))
# df_apple.head(1)
# # ERROR
df_apple.loc[0, "preco_atual_usd"] = "729.9"
df_apple.head(1)

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete,ano
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,729.9,43322.41,-1.6,sem promoção,In Stock,4.7,40,-6.81,465.81,2020

In [65]:
df_apple.loc[0, "preco_atual_usd"] = "NÃO INFORMADO"
df_apple["preco_atual_usd"] = pd.to_numeric(df_apple["preco_atual_usd"],
                                            errors="coerce")
df_apple.head(1)

,data,plataforma,categoria,modelo,condicao,preco_lancamento_usd,preco_lancamento_inr,preco_atual_usd,preco_atual_inr,percentual_desconto,evento_promocional,status_estoque,avaliacao,quantidade_avaliacoes,desconto_dolar,preco_com_taxa_frete,ano
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,NaN,43322.41,-1.6,sem promoção,In Stock,4.7,40,-6.81,465.81,2020

In [66]:
df_apple.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   data                   80000 non-null  datetime64[us]
 1   plataforma             80000 non-null  str
 2   categoria              80000 non-null  str
 3   modelo                 80000 non-null  str
 4   condicao               80000 non-null  str
 5   preco_lancamento_usd   80000 non-null  int64
 6   preco_lancamento_inr   80000 non-null  int64
 7   preco_atual_usd        79999 non-null  float64
 8   preco_atual_inr        80000 non-null  float64
 9   percentual_desconto    80000 non-null  float64
 10  evento_promocional     80000 non-null  str
 11  status_estoque         80000 non-null  str
 12  avaliacao              80000 non-null  float64
 13  quantidade_avaliacoes  80000 non-null  int64
 14  desconto_dolar         80000 non-null  float64
 15  preco_com_taxa_frete   80000 non-null  float64
 16  ano                    80000 non-null  int32
dtypes: datetime64[us](1), float64(6), int32(1), int64(3), str(6)
memory usage: 10.1 MB

In [67]:
df_apple.isna().sum()

data                     0
plataforma               0
categoria                0
modelo                   0
condicao                 0
preco_lancamento_usd     0
preco_lancamento_inr     0
preco_atual_usd          1
preco_atual_inr          0
percentual_desconto      0
evento_promocional       0
status_estoque           0
avaliacao                0
quantidade_avaliacoes    0
desconto_dolar           0
preco_com_taxa_frete     0
ano                      0
dtype: int64

In [ ]:
# data                     0
# plataforma               0
# categoria                0
# modelo                   0
# condicao                 0
# preco_lancamento_usd     0
# preco_lancamento_inr     0
# preco_atual_usd          1
# preco_atual_inr          0
# percentual_desconto      0
# evento_promocional       0
# status_estoque           0
# avaliacao                0
# quantidade_avaliacoes    0
# desconto_dolar           0
# preco_com_taxa_frete     0
# ano                      0
# dtype: int64